### ISSUE TITLE
AutomatedTesting bug report

### ISSUE THREAD

**Issue by Fredericwu** [FeixiDev/VersaSDSToolset#74]
**AutomatedTesting Question Feedback**
Test program hang and delete resources is not clean

**To Reproduce**
1. Go to VersaSDSToolset/AutomatedTesting/ directory
2. Edit test_quorum.yaml file
3. Execute program

**Expected behavior**
1.Program hang for an hour
![截屏2022-04-25 下午4 22 26](https://user-images.githubusercontent.com/41657047/165049623-b9fe8f30-ec36-49d2-b74a-702b80473755.png)

2.Delete resources is not clean 
![截屏2022-04-25 下午4 26 21](https://user-images.githubusercontent.com/41657047/165051083-6716b79e-562e-488c-9b06-c0d73db04620.png)

**Advice**
1.无论测试成功还是失败，需有相应的信息提示！
2.User guide需对“versaplx配置项中若无sp配置”这个用例添加说明，若是这个场景需将配置文件中的sp: <storagepool name>字段删除；
3.邮件通知如何设置？（目前没尝试成功）

**Comment by mattie-feng** [comment]
测试环境网络问题，非工具Bug
